//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpectreTool.ViewModel.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpectreTool.ViewModel.Localization.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;b&gt;Youtube&lt;/b&gt;&lt;br&gt;&lt;br&gt;&lt;a href=&quot;https://www.youtube.com/watch?v=Xfb8ht4UwOw&quot;&gt;Ай, Как Просто! : Уязвимость в процессорах Intel, AMD и ARM. Разбираемся с Meltdown и Spectre!&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;a href=&quot;https://www.youtube.com/watch?v=GgJwglipbqA&quot;&gt;Дмитрий Бачило : Уязвимость в процессорах Intel (и AMD, и ARM). Meltdown и Spectre&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;a href=&quot;https://www.youtube.com/watch?v=GgJwglipbqA&quot;&gt;PRO Hi-Tech : Бреши Meltdown и Spectre в процессорах Intel и AMD - тест в играх после патча&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;b&gt;Хабрахабр&lt;/b&gt;&lt;br&gt;&lt;br&gt;&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string AdditionalLinksDetails {
            get {
                return ResourceManager.GetString("AdditionalLinksDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БИОС.
        /// </summary>
        internal static string BiosInformation {
            get {
                return ResourceManager.GetString("BiosInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BpbDisabledNoHardwareSupport.
        /// </summary>
        internal static string BpbDisabledNoHardwareSupport {
            get {
                return ResourceManager.GetString("BpbDisabledNoHardwareSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BpbDisabledSystemPolicy.
        /// </summary>
        internal static string BpbDisabledSystemPolicy {
            get {
                return ResourceManager.GetString("BpbDisabledSystemPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BpbEnabled.
        /// </summary>
        internal static string BpbEnabled {
            get {
                return ResourceManager.GetString("BpbEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speculation control settings for CVE-2017-5715 [branch target injection].
        /// </summary>
        internal static string BtiCheckResults {
            get {
                return ResourceManager.GetString("BtiCheckResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch target injection mitigation is disabled by absence of hardware support:.
        /// </summary>
        internal static string BtiDisabledByNoHardwareSupport {
            get {
                return ResourceManager.GetString("BtiDisabledByNoHardwareSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch target injection mitigation is disabled by system policy:.
        /// </summary>
        internal static string BtiDisabledBySystemPolicy {
            get {
                return ResourceManager.GetString("BtiDisabledBySystemPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аппаратная поддержка смягчения манипуляции ветвями ветвления.
        /// </summary>
        internal static string BtiHardwareSupport {
            get {
                return ResourceManager.GetString("BtiHardwareSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows OS support for branch target injection mitigation is enabled.
        /// </summary>
        internal static string BtiWindowsSupportEnabled {
            get {
                return ResourceManager.GetString("BtiWindowsSupportEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support for branch target injection mitigation is present.
        /// </summary>
        internal static string BtiWindowsSupportPresent {
            get {
                return ResourceManager.GetString("BtiWindowsSupportPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты проверки.
        /// </summary>
        internal static string CheckDetails {
            get {
                return ResourceManager.GetString("CheckDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процессор.
        /// </summary>
        internal static string CpuInformation {
            get {
                return ResourceManager.GetString("CpuInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HwMode1Present.
        /// </summary>
        internal static string HwMode1Present {
            get {
                return ResourceManager.GetString("HwMode1Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HwMode2Present.
        /// </summary>
        internal static string HwMode2Present {
            get {
                return ResourceManager.GetString("HwMode2Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HwReg1Enumerated.
        /// </summary>
        internal static string HwReg1Enumerated {
            get {
                return ResourceManager.GetString("HwReg1Enumerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HwReg2Enumerated.
        /// </summary>
        internal static string HwReg2Enumerated {
            get {
                return ResourceManager.GetString("HwReg2Enumerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Meltdown (CVE-2017-5754).
        /// </summary>
        internal static string KvaCheckResults {
            get {
                return ResourceManager.GetString("KvaCheckResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support for kernel VA shadow is enabled.
        /// </summary>
        internal static string KvaShadowEnabled {
            get {
                return ResourceManager.GetString("KvaShadowEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KvaShadowInvpcid.
        /// </summary>
        internal static string KvaShadowInvpcid {
            get {
                return ResourceManager.GetString("KvaShadowInvpcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware not requires kernel VA shadowing.
        /// </summary>
        internal static string KvaShadowNotRequired {
            get {
                return ResourceManager.GetString("KvaShadowNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KvaShadowPcid.
        /// </summary>
        internal static string KvaShadowPcid {
            get {
                return ResourceManager.GetString("KvaShadowPcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support for PCID performance optimization is enabled [not required for security].
        /// </summary>
        internal static string KvaShadowPcidEnabled {
            get {
                return ResourceManager.GetString("KvaShadowPcidEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support for kernel VA shadow is present.
        /// </summary>
        internal static string KvaShadowPresent {
            get {
                return ResourceManager.GetString("KvaShadowPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KvaShadowUserGlobal.
        /// </summary>
        internal static string KvaShadowUserGlobal {
            get {
                return ResourceManager.GetString("KvaShadowUserGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производитель.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее!.
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Защищен ли я?.
        /// </summary>
        internal static string MySafety {
            get {
                return ResourceManager.GetString("MySafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     Уязвимости подвержены практически все современные процессоры &lt;a href=&quot;https://security-center.intel.com/advisory.aspx?intelid=intel-sa-00088&amp;amp;languageid=en-fr&quot;&gt;Intel&lt;/a&gt;, &lt;a href=&quot;https://www.amd.com/ru/corporate/speculative-execution/&quot;&gt;AMD&lt;/a&gt; и &lt;a href=&quot;https://developer.arm.com/support/security-update&quot;&gt;ARM&lt;/a&gt;. Майкрософт уже &lt;a href=&quot;https://support.microsoft.com/ru-ru/help/4073757/protect-your-windows-devices-against-spectre-meltdown&quot;&gt;выпустил описание проблемы и необходимые обновления&lt;/a&gt;, кото [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MySafetyDetails {
            get {
                return ResourceManager.GetString("MySafetyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операционная система.
        /// </summary>
        internal static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата выпуска.
        /// </summary>
        internal static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ревизия.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SmepPresent.
        /// </summary>
        internal static string SmepPresent {
            get {
                return ResourceManager.GetString("SmepPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Системная информация.
        /// </summary>
        internal static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     Уязвимости находили и будут находить, но все ранее найденные уязвимости были на программном уровне. Это значит, что достаточно было обновить программу и проблема решена. К тому же их использование требовало вызова специального кода, который умеют определять и блокировать антивирусы.
        ///
        ///    Со Spectre и Meldtown все совсем иначе. Здесь уязвимость обнаружена на уровне архитектуры процессора, а значит просто скачать обновление и решить проблему не получится. И хуже всего то, что для этого не нужны вирусы и [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string VulnerabilitiesDetails {
            get {
                return ResourceManager.GetString("VulnerabilitiesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что произошло?.
        /// </summary>
        internal static string WhatHappened {
            get {
                return ResourceManager.GetString("WhatHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     В начале лета 2017 года &lt;a href=&quot;https://googleprojectzero.blogspot.ru&quot;&gt;Проектом Зеро&lt;/a&gt; были &lt;a href=&quot;https://googleprojectzero.blogspot.ru/2018/01/reading-privileged-memory-with-side.html&quot;&gt;обнаружены&lt;/a&gt; две уязвимости абсолютно нового типа. Они получили названия &lt;a href=&quot;https://ru.wikipedia.org/wiki/Spectre_(уязвимость)&quot;&gt;Spectre&lt;/a&gt; (&lt;a href=&quot;http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2017-5753&quot;&gt;CVE-2017-5715&lt;/a&gt;, &lt;a href=&quot;http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2017-5753&quot;&gt;CVE-2017 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WhatHappenedDetails {
            get {
                return ResourceManager.GetString("WhatHappenedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is Meldtown and Spectre ?.
        /// </summary>
        internal static string WhatIsVulnerabilities {
            get {
                return ResourceManager.GetString("WhatIsVulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     Использование этих уязвимостей позволяет совершенно незаметно украсть, логины,емейлы, пароли, данные пластиковых карт и прочую важную информацию..
        /// </summary>
        internal static string WhatIsVulnerabilitiesDetails {
            get {
                return ResourceManager.GetString("WhatIsVulnerabilitiesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на И антивирус от этого не спасет..
        /// </summary>
        internal static string WhatIsVulnerabilitiesDetailsNoAntivirus {
            get {
                return ResourceManager.GetString("WhatIsVulnerabilitiesDetailsNoAntivirus", resourceCulture);
            }
        }
    }
}
